# Generated by Django 6.1 on 2026-09-06 09:12

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Введите номер телефона", max_length=128, region=None, verbose_name="Телефон"
            ),
        ),
    ]
