# Generated by Django 6.1 on 2026-09-03 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Укажите номер стола", unique=True, verbose_name="Номер стола"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Максимальное количество гостей", verbose_name="Количество мест"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("VIP", "Премиум"), ("standard", "Стандарт")],
                        help_text="Укажите категорию стола",
                        max_length=25,
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_at",
                    models.DateTimeField(
                        help_text="Укажите время начала бронирования", verbose_name="Время начала бронирования"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        help_text="Укажите время окончания бронирования", verbose_name="Время окончания бронирования"
                    ),
                ),
                (
                    "guests",
                    models.PositiveIntegerField(
                        help_text="Укажите количество гостей", verbose_name="Количество гостей"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("cancelled", "Отменено"),
                            ("completed", "Завершено"),
                        ],
                        default="pending",
                        help_text="Укажите статус бронирования",
                        max_length=25,
                        verbose_name="Статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, help_text="Укажите комментарий", verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите посетителя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Посетитель",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="Укажите стол",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="restaurant.table",
                        verbose_name="Стол",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-created_at"],
            },
        ),
    ]
