# Generated by Django 6.1 on 2026-09-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Укажите название услуги", max_length=250, verbose_name="Название"),
                ),
                ("description", models.TextField(help_text="Укажите описание услуги.", verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше услуга в списке",
                        verbose_name="Порядок отображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга ресторана",
                "verbose_name_plural": "Услуги ресторана",
                "ordering": ["order", "name"],
            },
        ),
    ]
