# Generated by Django 6.1 on 2026-09-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_restaurantservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantservice",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Чем меньше число, тем выше услуга в списке",
                unique=True,
                verbose_name="Порядок отображения",
            ),
        ),
    ]
