# Generated by Django 6.1 on 2026-09-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_alter_restaurantservice_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(help_text="Введите имя", max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(help_text="Введите фамилию", max_length=100, verbose_name="Фамилия")),
                (
                    "phone",
                    models.CharField(help_text="Введите номер телефона", max_length=100, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, help_text="Укажите почту", max_length=254, verbose_name="Почта"),
                ),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
                "ordering": ["first_name", "last_name"],
            },
        ),
    ]
