# Generated by Django 6.1 on 2026-09-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_contactform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactform",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name": "контакт обратной связи",
                "verbose_name_plural": "контакты обратной связи",
            },
        ),
    ]
