# Generated by Django 6.1 on 2026-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_contactform_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Укажите почту", max_length=254, unique=True, verbose_name="Почта"
            ),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="phone",
            field=models.CharField(
                help_text="Введите номер телефона", max_length=100, unique=True, verbose_name="Телефон"
            ),
        ),
    ]
