# Generated by Django 6.1 on 2026-09-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_alter_contactform_email_alter_contactform_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantEmployee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото сотрудника",
                        null=True,
                        upload_to="restaurant/photo_employee",
                        verbose_name="Фото",
                    ),
                ),
                ("first_name", models.CharField(help_text="Введите имя", max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(help_text="Введите фамилию", max_length=100, verbose_name="Фамилия")),
                (
                    "post",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cleaner", "Уборщица"),
                            ("waiter", "Официант"),
                            ("bartender", "Бармен"),
                            ("cook", "Повар"),
                            ("head_chef", "Шеф-повар"),
                            ("director", "Директор"),
                            ("administrator", "Администратор"),
                        ],
                        help_text="Укажите должность",
                        max_length=100,
                        null=True,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "work_experience",
                    models.PositiveIntegerField(
                        blank=True, help_text="Укажите опыт работы (лет)", null=True, verbose_name="Опыт"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше сотрудник в списке",
                        verbose_name="Порядок отображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "контакт обратной связи",
                "verbose_name_plural": "контакты обратной связи",
                "ordering": ["order", "post", "work_experience", "first_name", "last_name"],
            },
        ),
    ]
