# Generated by Django 6.1 on 2026-09-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_restaurantemployee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurantemployee",
            options={
                "ordering": ["order", "post", "work_experience", "first_name", "last_name"],
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
