# Generated by Django 6.1 on 2026-09-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_alter_restaurantemployee_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurantemployee",
            options={
                "ordering": ["order", "last_name"],
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
