# Generated by Django 6.1 on 2026-09-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0009_alter_restaurantemployee_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={"ordering": ("-number",), "verbose_name": "Стол", "verbose_name_plural": "Столы"},
        ),
    ]
