# Generated by Django 6.1 on 2026-09-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0010_alter_table_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={"ordering": ("number",), "verbose_name": "Стол", "verbose_name_plural": "Столы"},
        ),
    ]
