# Generated by Django 6.1 on 2026-09-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0011_alter_table_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Token"),
        ),
    ]
