# Generated by Django 6.1 on 2026-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentRestaurantAbout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image_history",
                    models.ImageField(
                        help_text="Загрузите для истории ресторана",
                        upload_to="content/history_rest",
                        verbose_name="Фото для истории",
                    ),
                ),
                (
                    "history_title",
                    models.CharField(
                        help_text="Введите заголовок для истории ресторана.",
                        max_length=500,
                        verbose_name="Заголовок истории ресторана.",
                    ),
                ),
                ("history_p1", models.TextField(help_text="Введите историю ресторана", verbose_name="Первый пункт")),
                (
                    "history_p2",
                    models.TextField(
                        blank=True,
                        help_text="Введите историю ресторана. Для нового абзаца оставьте пустую строку.",
                        verbose_name="Второй пункт",
                    ),
                ),
                (
                    "chef_image",
                    models.ImageField(
                        help_text="Загрузите для истории Шеф-повара",
                        upload_to="content/history_chef",
                        verbose_name="Фото для Шеф-повара",
                    ),
                ),
                (
                    "chef_title",
                    models.CharField(
                        help_text="Укажите заголовок для истории о Шеф-поваре",
                        max_length=500,
                        verbose_name="Заголовок истории Шеф-повара",
                    ),
                ),
                ("chef_p1", models.TextField(help_text="Введите историю шефа", verbose_name="История шефа (видимое)")),
                (
                    "chef_p2",
                    models.TextField(
                        help_text="Введите историю шефа. Для нового абзаца оставьте пустую строку.",
                        verbose_name="История шефа (скрытое)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница 'О ресторане'",
            },
        ),
    ]
