# Generated by Django 6.1 on 2026-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrestaurantabout",
            name="mission",
            field=models.TextField(
                blank=True, help_text="Введите основное содержание (миссию).", null=True, verbose_name="Миссия"
            ),
        ),
        migrations.AddField(
            model_name="contentrestaurantabout",
            name="mission_title",
            field=models.CharField(
                blank=True,
                help_text="Введите заголовок для миссии",
                max_length=250,
                null=True,
                verbose_name="Заголовок миссии",
            ),
        ),
        migrations.AddField(
            model_name="contentrestaurantabout",
            name="value_title",
            field=models.CharField(
                blank=True, help_text="Введите заголовок ценностей", null=True, verbose_name="Заголовок ценностей"
            ),
        ),
        migrations.AddField(
            model_name="contentrestaurantabout",
            name="values",
            field=models.TextField(
                blank=True,
                help_text="Каждую ценность указывайте с новой строки",
                null=True,
                verbose_name="Ценности ресторана",
            ),
        ),
        migrations.AlterField(
            model_name="contentrestaurantabout",
            name="chef_title",
            field=models.CharField(
                help_text="Введите заголовок для истории о Шеф-поваре",
                max_length=500,
                verbose_name="Заголовок истории Шеф-повара",
            ),
        ),
    ]
