# Generated by Django 6.1 on 2026-09-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_contentrestaurantabout_mission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentrestaurantabout",
            name="mission",
            field=models.TextField(help_text="Введите основное содержание (миссию).", verbose_name="Миссия"),
        ),
        migrations.AlterField(
            model_name="contentrestaurantabout",
            name="mission_title",
            field=models.CharField(
                help_text="Введите заголовок для миссии", max_length=250, verbose_name="Заголовок миссии"
            ),
        ),
        migrations.AlterField(
            model_name="contentrestaurantabout",
            name="value_title",
            field=models.CharField(help_text="Введите заголовок ценностей", verbose_name="Заголовок ценностей"),
        ),
        migrations.AlterField(
            model_name="contentrestaurantabout",
            name="values",
            field=models.TextField(
                help_text="Каждую ценность указывайте с новой строки", verbose_name="Ценности ресторана"
            ),
        ),
    ]
