# Generated by Django 6.1 on 2026-09-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_contentrestaurantabout_mission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentRestaurantHome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rest_image",
                    models.ImageField(
                        help_text="Загрузите для истории ресторана",
                        upload_to="content/main_rest",
                        verbose_name="Фото для истории",
                    ),
                ),
                (
                    "rest_name",
                    models.CharField(
                        help_text="Введите название ресторана", max_length=250, verbose_name="Название ресторана"
                    ),
                ),
                (
                    "rest_title",
                    models.CharField(
                        help_text="Введите описывающее ресторан предисловие",
                        max_length=500,
                        verbose_name="Короткое предисловие",
                    ),
                ),
                (
                    "rest_description",
                    models.TextField(help_text="Введите описание ресторана", verbose_name="Описание"),
                ),
                (
                    "chef_headline",
                    models.CharField(help_text="Укажите заголовок карточки", max_length=250, verbose_name="Заголовок"),
                ),
                (
                    "chef_history",
                    models.TextField(help_text="Введите краткую историю", verbose_name="Короткая история шеф-повара"),
                ),
                (
                    "chef_awards",
                    models.TextField(
                        help_text="Введите награды. Каждую указывайте с новой строки", verbose_name="Награды"
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница 'Главная'",
            },
        ),
    ]
