# Generated by Django 6.1 on 2026-09-13 17:11

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_contentrestauranthome"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseContentRestaurant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "logo",
                    models.ImageField(
                        help_text="Загрузите логотип заведения.", upload_to="content/logo", verbose_name="Логотип"
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        help_text="Загрузите фоновое изображение заднего фона",
                        upload_to="content/site",
                        verbose_name="Фоновое изображение",
                    ),
                ),
                (
                    "rest_name",
                    models.CharField(
                        help_text="Введите название заведения", max_length=250, verbose_name="Название заведения"
                    ),
                ),
                ("rest_title", models.TextField(help_text="Введите небольшое ", verbose_name="Короткий заголовок")),
                (
                    "address",
                    models.CharField(help_text="Введите адрес ресторана", max_length=250, verbose_name="Адрес"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Введите номер телефона", max_length=128, region=None, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите почту ресторана", max_length=254, verbose_name="Почта ресторана"
                    ),
                ),
            ],
            options={
                "verbose_name": "Общий контент сайта",
                "verbose_name_plural": "Общий контент сайта",
            },
        ),
        migrations.AlterModelOptions(
            name="contentrestaurantabout",
            options={"verbose_name": "Страница 'О ресторане'", "verbose_name_plural": "Страница 'О ресторане'"},
        ),
        migrations.AlterModelOptions(
            name="contentrestauranthome",
            options={"verbose_name": "Страница 'Главная'", "verbose_name_plural": "Страница 'Главная'"},
        ),
    ]
