# Generated by Django 6.1 on 2026-09-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_basecontentrestaurant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecontentrestaurant",
            name="rest_title",
            field=models.TextField(
                help_text="Введите небольшое и говорящее предложение о ресторане", verbose_name="Короткий заголовок"
            ),
        ),
    ]
